### PR TITLE
Increment build to retrigger CI.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by jakirkham** [comment]
This shouldn't be necessary as you have permissions to restart the CIs directly. Have you tried?

**Comment by jgoppert** [comment]
@jakirkham I did try to restart, clicked the button, said it failed.

**Comment by jakirkham** [comment]
Really? Have you enabled CircleCI on your GitHub account?

**Comment by jgoppert** [comment]
@jakirkham Once I enabled CircleCI on github it worked.

**Comment by jakirkham** [comment]
Glad that worked. Seems the build passed too.

Have raised this upstream issue ( https://discuss.circleci.com/t/docker-pull-fails-somtimes/7181 ) showing a few cases where CircleCI fails to pull the Docker image for whatever reason.

**Pull request closed without merging**
